name: WorldResetPlugin
version: '1.2'
main: com.ashkiano.worldresetplugin.WorldResetPlugin
api-version: '1.16'
commands:
  resetworld:
    description: Removes and regenerates any world by name.
    usage: /<command> <worldName>
    permission: worldreset.use